name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Zip extension
        run: zip -r chrome-extension.zip chrome-extension/

      - name: Zip server
        run: zip -r server.zip server/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@3bb12739c298aeb8a4eeaf626c5b8d85266b0e65 # v2
        with:
          files: |
            chrome-extension.zip
            server.zip
            install.sh
            uninstall.sh
          generate_release_notes: true
